// MIT License
//
// Copyright (c) 2026 John Andrew McInnes
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

//// a timer generated by an AI chatbot. thanks!
//
#include <chrono>
#include <cstdint>
#include <sys/timerfd.h>
#include <unistd.h>

class SimpleTimer {
public:
    SimpleTimer() : is_active(false) {}

    void start() {
        start_time = std::chrono::steady_clock::now();
        is_active = true;
    }

    void stop() {
        is_active = false;
    }

    void restart(){
        start();
    }

    bool isRunning() const {
        return is_active;
    }

    template<typename Duration = std::chrono::milliseconds>
    auto elapsed() const {
        if (!is_active) {
            return Duration(0);
        }
        auto end_time = std::chrono::steady_clock::now();
        return std::chrono::duration_cast<Duration>(end_time - start_time);
    }

    int64_t elapsed_ms() const {
        int64_t e_ms = elapsed().count();
        return e_ms;
    }

    int64_t elapsed_sec() const {
        int64_t e_sec = elapsed_ms() / 1000;
        return e_sec;
    }

private:
    std::chrono::steady_clock::time_point start_time;
    bool is_active;
};


// uses Linux timerfd_ API to manage an accurate recurring timer.
// Is timerfd_gettime threadsafe? webservice thread is using it. should be right? todo
class FDTimer{
public:
    FDTimer() : TimerID(-1) {}

    bool Create(){
        if ( TimerID != -1 ){
            Close();
        }

        TimerID = timerfd_create(CLOCK_REALTIME, 0);
        if (TimerID == -1) {
            perror("timerfd_create");
            return false;
        }
        return true; // success
    }

    bool Start( int sec_to_start, int interval_sec ){
        struct itimerspec ts;
        ts.it_value.tv_sec = sec_to_start;
        ts.it_value.tv_nsec = 0;
        ts.it_interval.tv_sec = interval_sec;
        ts.it_interval.tv_nsec = 0;

        if (timerfd_settime(TimerID, 0, &ts, NULL) == -1) {
            perror("timerfd_settime");
            return false;
        }
        return true; // success
    }

    void Close(){
        close(TimerID);
        TimerID = -1;
    }

    // @brief blocking wait until next firing of timer
    // @returns number of times timer has fired since last check
    int Wait(){
        uint64_t num_events = 0;
        if ( read(TimerID, &num_events, sizeof(num_events)) != 0 ){
            perror("FDTimer read");
        }
        return num_events;
    }

    // @brief get current timer interval_sec
    int GetIntervalSeconds(){
        itimerspec curr_val;
        if ( timerfd_gettime(TimerID, &curr_val) == -1 ){
            perror("timerfd_gettime");
            return 0;
        }

        return curr_val.it_interval.tv_sec;
        //+ curr_val.it_interval.tv_nsec / 100000;
    }

    // @brief get # seconds left until next timer event fire
    int GetSecondsLeft(){
        itimerspec curr_val;
        if ( timerfd_gettime(TimerID, &curr_val) == -1 ){
            perror("timerfd_gettime");
            return 0;
        }

        return curr_val.it_value.tv_sec;
        //+ curr_val.it_value.tv_nsec / 100000;
    }

    // @brief get # milliseconds left until next timer event fire
    int GetMSLeft(){
        itimerspec curr_val;
        if ( timerfd_gettime(TimerID, &curr_val) == -1 ){
            perror("timerfd_gettime");
            return 0;
        }

        return curr_val.it_value.tv_sec * 1000 + curr_val.it_value.tv_nsec / 1000000;
    }

    // @brief get # of seconds that have elapsed since last timer event
    int GetSeconds(){
        itimerspec curr_val;
        if ( timerfd_gettime(TimerID, &curr_val) == -1 ){
            perror("timerfd_gettime");
            return 0;
        }

        return curr_val.it_interval.tv_sec - curr_val.it_value.tv_sec;
        //+ curr_val.it_value.tv_nsec / 100000;
    }

    // get # of milliseconds since last timer event
    int GetMS(){
        itimerspec curr_val;
        if ( timerfd_gettime(TimerID, &curr_val) == -1 ){
            perror("timerfd_gettime");
            return 0;
        }

        int32_t interval_ms = curr_val.it_interval.tv_sec * 1000 + curr_val.it_interval.tv_nsec / 1000000;
        int32_t expiration_ms = curr_val.it_value.tv_sec * 1000 + curr_val.it_value.tv_nsec / 1000000;
        int32_t elapsed_ms = interval_ms - expiration_ms;
        return elapsed_ms;
    }

private:
    int TimerID;
};
